name: Trunk.io

on:
  push:
    branches:
      - main
      - trunk-merge/**
  pull_request:
    branches:
      - main
      - "*"
permissions: read-all

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
